[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "longdin-noise"
version = "0.1.1"
description = "A diffusion-driven procedural noise library."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "numba",
]

[[project.authors]]
name = "Drew Longdin"
email = "longdindrew@gmail.com"

[project.urls]
Homepage = "https://github.com/drewlongdin-dev/longdin-noise"
